### ISSUE TITLE
No config

### ISSUE THREAD

**Issue by FatherSarge** [mooziii/tpshud-fabric#11] opened 2023-11-08 00:15 UTC
Hi,

I believe this issue has resurface: https://github.com/mooziii/tpshud-fabric/issues/7

On fabric for 1.19.2
I'm on version 1.6.0+ (1.19.2) of the mod
with modmenu 4.2.0 beta2 and YACL 2.2.0 installed. TPS hud shows up but the config button is missing.

Any help would be appreciated!

**Comment by mooziii** [comment] 2023-11-08 13:19
yeah I believe this is a duplicate of #7, could you try updating to the 1.19.3 version or even newer (if that's possible for you)?

**Comment by FatherSarge** [comment] 2023-11-08 19:41
> yeah I believe this is a duplicate of #7, could you try updating to the 1.19.3 version or even newer (if that's possible for you)?

Unfortunately I cannot, this is in concert with a modpack our server is using running on 1.19.2 (dictated by the major mods we are running)

It's not a huge deal if fixing it isn't a priority, just wanted to let you know. We've used your mod before on our 1.18.2 version of the server and it worked great for the couple of us that wanted the TPS info so we could yell at the admin about it :P

**Closed as not planned** 2023-11-19 18:43 UTC
Labels: bug, duplicate
